# Generated by Django 4.1.7 on 2023-03-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=200)),
                ("salary", models.IntegerField()),
                ("work_hours", models.IntegerField()),
            ],
        ),
    ]
