# Generated by Django 4.2 on 2023-04-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_date',
            field=models.DateField(default='2023-5-4'),
        ),
    ]
