# Generated by Django 4.1.7 on 2023-04-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_member_user_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="member", name="test", field=models.BooleanField(default=True),
        ),
    ]
