# Generated by Django 4.2 on 2023-04-27 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_task_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employees.managers'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
