# Generated by Django 4.2 on 2023-04-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_task_assigned_by_alter_task_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
