# Generated by Django 4.2 on 2023-04-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_task_assigned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_date',
            field=models.DateField(default='2023-2-4', null=True),
        ),
    ]
