# Generated by Django 4.2 on 2023-04-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_task_assigned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='manager_approved',
            field=models.BooleanField(default=False),
        ),
    ]
